export type ColumnTypes = 'smallint'
  | 'integer'
  | 'bigint'
  | 'decimal'
  | 'numeric'
  | 'real'
  | 'double'
  | 'smallserial'
  | 'serial'
  | 'bigserial'
  | 'varchar'
  | 'text'
  | 'timestamp'
  | 'date'
  | 'boolean'
  | 'enum'
  | 'uuid';